### ISSUE TITLE
bug when PATH not defined

### ISSUE THREAD

**Issue by ihucos** [ihucos/plash#41]
(venv) [resu@localhost plash]$ env -i plash run -U  -- chown 0:0 /var/cache/apt/archives/partial/
Traceback (most recent call last):
  File "/bin/plash", line 25, in <module>
    os.environ['PATH'] = '{}:{}'.format(libexec, os.environ['PATH'])
  File "/usr/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'PATH'
(venv) [resu@localhost plash]$

**Comment by ihucos** [comment]
triggered by
 env -i plash run -U
