### ISSUE TITLE
handle bad rootfs better

### ISSUE THREAD

**Issue by ihucos** [ihucos/plash#80]
if for example `/home` is missing, the following error happens:
```
$ plash run 157
```
mount: /home/ihucos/.plashdata/mnt/home: mount point does not exist.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/plash/libexec/plash-runopts", line 92, in <module>
    os.path.join(mountpoint, mount.lstrip('/'))
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mount', '--rbind', '/home', '/home/ihucos/.plashdata/mnt/home']' returned non-zero exit status 32.
```
One elegant/interesting/lightweight/hacky solution is to have the home folder in the root container!

**Comment by ihucos** [comment]
The newish C implementation of runopts fixes this.
