### ISSUE TITLE
Can not run inside ihucos/bchroot

### ISSUE THREAD

**Issue by ihucos** [ihucos/plash#84]
It's funny, I swear this happens only sometimes.
The problem is, that /etc/resolv.conf is already a mount to the file outside the chroot.
```
ihucos-MacBookPro:~/bchroot# plash -A
mount: mounting /etc/resolv.conf on /var/lib/plash/mnt/etc/resolv.conf failed: No such file or directory
Traceback (most recent call last):
  File "/home/ihucos/plash/plash/libexec/plash-runopts", line 92, in <module>
    os.path.join(mountpoint, mount.lstrip('/'))
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['mount', '--rbind', '/etc/resolv.conf', '/var/lib/plash/mnt/etc/resolv.conf']' returned non-zero exit status 255.
ihucos-MacBookPro:~/bchroot# 

```

**Comment by ihucos** [comment]
Does not seem to happen anymore - possibly because the mount syscall is now called directly
