### ISSUE TITLE
Plash can not be called if not in PATH

### ISSUE THREAD

**Issue by ihucos** [ihucos/plash#86]
```
ihucos@ihucos-MacBookPro:~/bchroot$ ~/.local/bin/plash -U
plash error: plash.macros.froms: from: [Errno 2] No such file or directory: 'plash': 'plash' (FileNotFoundError)
ihucos@ihucos-MacBookPro:~/bchroot$ PLASH_DEBUG=1 ~/.local/bin/plash -U
Traceback (most recent call last):
  File "/home/ihucos/.local/lib/python3.6/site-packages/plash/libexec/plash-eval", line 70, in <module>
    script = eval.eval(lsp)
  File "/home/ihucos/.local/lib/python3.6/site-packages/plash/eval.py", line 83, in eval
    res = macro(*args)
  File "/home/ihucos/.local/lib/python3.6/site-packages/plash/macros/shortcuts.py", line 23, in func
    return eval(macro[:-1] + [macro[-1] + args])
  File "/home/ihucos/.local/lib/python3.6/site-packages/plash/eval.py", line 83, in eval
    res = macro(*args)
  File "/home/ihucos/.local/lib/python3.6/site-packages/plash/macros/froms.py", line 76, in from_
    return from_lxc(image)
  File "/home/ihucos/.local/lib/python3.6/site-packages/plash/macros/froms.py", line 17, in wrapper
    container_id = func(*args)
  File "/home/ihucos/.local/lib/python3.6/site-packages/plash/macros/froms.py", line 39, in from_lxc
    image]).decode().rstrip('\n')
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'plash': 'plash'
ihucos@ihucos-MacBookPro:~/bchroot$ 
```

**Comment by ihucos** [comment]
its now working, after some stuff was rewritten in C. But this actually means, that it only fails more gracful but with less information, because python3 then can not be found
