### ISSUE TITLE
plash build failing on 'tumbleweed' version handling

### ISSUE THREAD

**Issue by joaompinto** [ihucos/plash#93]
18:04 $ plash build --from alpine
Traceback (most recent call last):
  File "/home/jpinto/.local/lib/python3.7/site-packages/plash/libexec/plash-import-lxc", line 90, in <module>
    newest = sorted(versions, key=lambda v: float(v.replace('x', '0')))[-1]
  File "/home/jpinto/.local/lib/python3.7/site-packages/plash/libexec/plash-import-lxc", line 90, in <lambda>
    newest = sorted(versions, key=lambda v: float(v.replace('x', '0')))[-1]
ValueError: could not convert string to float: 'tumbleweed'
plash error: plash.macros.froms: from: Command '['plash', 'import-lxc', 'alpine']' returned non-zero exit status 1. (CalledProcessError)

**Comment by joaompinto** [comment]
The PR fails while testing the current version on Travis (before getting the fix).
