### ISSUE TITLE
plash help fails when installed via pip with --user

### ISSUE THREAD

**Issue by joaompinto** [ihucos/plash#95]
```
18:36 $ pip install --user plash; plash --help
Requirement already satisfied: plash in ./.local/lib/python3.7/site-packages (0.1.dev0)
Traceback (most recent call last):
  File "/home/jpinto/.local/bin/plash", line 27, in <module>
    os.execlp(binfile, binfile, *sys.argv[2:])
  File "/usr/lib/python3.7/os.py", line 554, in execlp
    execvp(file, args)
  File "/usr/lib/python3.7/os.py", line 571, in execvp
    _execvpe(file, args)
  File "/usr/lib/python3.7/os.py", line 594, in _execvpe
    exec_func(file, *argrest)
PermissionError: [Errno 13] Permission denied
```

**Comment by ihucos** [comment]
Hello

Could not reproduce in my Ubuntu Bionic:
```
ihucos@ihucos-MacBookPro:/$ pip3 install --user plash
Collecting plash
  Downloading https://files.pythonhosted.org/packages/b2/1e/2514e91c9af4256b2eb53c0f382eb459b3e59c9fd6c8d8f98de556561479/plash-1.1592-py3-none-any.whl (753kB)
    100% |████████████████████████████████| 757kB 903kB/s 
Installing collected packages: plash
Successfully installed plash-1.1592
ihucos@ihucos-MacBookPro:/$ plash -h
plash --help        List all available subcommands
plash --help-macros Lists all available macros
plash --version     Prints the version number
plash -h            List all available subcommands
plash add-layer     Stack a layer on top of a container
plash build         Builds a container
plash clean         Cleanup internal states
[...]
```

It seems to me, that you installed it from a local clone, since the version number he gives you `0.1.dev0` should be replaced by somethine like 1.xxx when plash is packaged for pip.

Try this:
```
$ pip uninstall plash
$ pip3 install --no-cache-dir --user plash
```

Be aware, that plash is moving away from pip (https://github.com/ihucos/plash/issues/12). I really don't like doing backward incompatible changes, but that will be an exception since plash is actually not a "typical" python project and need some things that would be difficult to fit in this format. If you are interested take a look at: https://github.com/ihucos/plash/tree/restructuring . Let me know, if this breaks your workflow.

Cheers,
ihucos

**Comment by joaompinto** [comment]
It worked after the reinstall thanks. I will follow up the "drop pip" issue :P
